import { Product } from './types';

export const POPULAR_CALIBERS = [
  "9mm Luger", "5.56 NATO", ".223 Rem", ".22 LR", ".308 Win", "7.62x39mm", ".45 ACP"
];

export const MOCK_LISTINGS: Product[] = [
  // --- AMMUNITION ---
  {
    id: '1',
    name: 'CCI Blazer Brass 9mm Luger 115gr FMJ',
    category: 'ammo',
    caliber: '9mm Luger',
    brand: 'CCI',
    grains: 115,
    roundCount: 1000,
    price: 239.00,
    cpr: 0.239,
    shippingScore: 10,
    shippingText: 'Free Shipping',
    retailer: 'Target Sports USA',
    retailerRating: 4.9,
    condition: 'New',
    casing: 'Brass',
    isSponsored: true,
    image: 'https://picsum.photos/200/200?random=1',
    lastUpdated: '1 min ago'
  },
  {
    id: '2',
    name: 'PMC X-TAC 5.56x45mm NATO 55gr FMJ-BT',
    category: 'ammo',
    caliber: '5.56 NATO',
    brand: 'PMC',
    grains: 55,
    roundCount: 1000,
    price: 449.50,
    cpr: 0.450,
    shippingScore: 9,
    shippingText: 'Free > $300',
    retailer: 'SGAmmo',
    retailerRating: 4.8,
    condition: 'New',
    casing: 'Brass',
    image: 'https://picsum.photos/200/200?random=2',
    lastUpdated: '3 mins ago'
  },
  {
    id: '3',
    name: 'Federal HST 9mm 124gr JHP (LE Box)',
    category: 'ammo',
    caliber: '9mm Luger',
    brand: 'Federal',
    grains: 124,
    roundCount: 50,
    price: 35.00,
    cpr: 0.70,
    shippingScore: 7,
    retailer: 'Bone Frog Gun Club',
    retailerRating: 4.7,
    condition: 'New',
    casing: 'Brass',
    image: 'https://picsum.photos/200/200?random=3',
    lastUpdated: '12 mins ago'
  },
  {
    id: '4',
    name: 'Tula 7.62x39mm 122gr FMJ Steel Case',
    category: 'ammo',
    caliber: '7.62x39mm',
    brand: 'Tula',
    grains: 122,
    roundCount: 1000,
    price: 380.00,
    cpr: 0.38,
    shippingScore: 5,
    shippingText: '$25 Flat Rate',
    retailer: 'Outdoor Limited',
    retailerRating: 4.5,
    condition: 'New',
    casing: 'Steel',
    image: 'https://picsum.photos/200/200?random=4',
    lastUpdated: '4 mins ago'
  },
  {
    id: '5',
    name: 'Remington .22 LR Golden Bullet 36gr HP',
    category: 'ammo',
    caliber: '.22 LR',
    brand: 'Remington',
    grains: 36,
    roundCount: 525,
    price: 34.99,
    cpr: 0.066,
    shippingScore: 8,
    retailer: 'MidwayUSA',
    retailerRating: 4.9,
    condition: 'New',
    casing: 'Brass',
    image: 'https://picsum.photos/200/200?random=5',
    lastUpdated: 'Just now'
  },
  {
    id: '6',
    name: 'AAC 5.56 NATO 77gr OTM Match',
    category: 'ammo',
    caliber: '5.56 NATO',
    brand: 'AAC',
    grains: 77,
    roundCount: 20,
    price: 11.99,
    cpr: 0.60,
    shippingScore: 6,
    retailer: 'Palmetto State Armory',
    retailerRating: 4.6,
    condition: 'New',
    casing: 'Brass',
    image: 'https://picsum.photos/200/200?random=6',
    lastUpdated: '25 mins ago'
  },
  {
    id: '7',
    name: 'Unknown Reloads 9mm Mix Bag',
    category: 'ammo',
    caliber: '9mm Luger',
    brand: 'Bubba\'s Hot Loads',
    grains: 115,
    roundCount: 500,
    price: 90.00,
    cpr: 0.18,
    shippingScore: 2,
    retailer: 'Sketchy Jim\'s',
    retailerRating: 2.1,
    condition: 'Reman',
    casing: 'Brass',
    image: 'https://picsum.photos/200/200?random=7',
    lastUpdated: '1 hour ago'
  },
  {
    id: '8',
    name: 'Winchester Super-X 12 Gauge 00 Buck',
    category: 'ammo',
    caliber: '12 Gauge',
    brand: 'Winchester',
    grains: 0,
    roundCount: 5,
    price: 6.99,
    cpr: 1.40,
    shippingScore: 8,
    retailer: 'Bass Pro',
    retailerRating: 4.5,
    condition: 'New',
    casing: 'Brass',
    image: 'https://picsum.photos/200/200?random=8',
    lastUpdated: '5 hours ago'
  },
  {
    id: '9',
    name: 'Fiocchi 12 Gauge 1oz Slug',
    category: 'ammo',
    caliber: '12 Gauge',
    brand: 'Fiocchi',
    grains: 437,
    roundCount: 10,
    price: 9.50,
    cpr: 0.95,
    shippingScore: 7,
    retailer: 'Lucky Gunner',
    retailerRating: 4.9,
    condition: 'New',
    casing: 'Brass',
    image: 'https://picsum.photos/200/200?random=9',
    lastUpdated: '2 hours ago'
  },
  {
    id: '10',
    name: 'Hornady Precision Hunter 6.5 Creedmoor 143gr ELD-X',
    category: 'ammo',
    caliber: '6.5 Creedmoor',
    brand: 'Hornady',
    grains: 143,
    roundCount: 20,
    price: 42.99,
    cpr: 2.15,
    shippingScore: 9,
    retailer: 'MidwayUSA',
    retailerRating: 4.9,
    condition: 'New',
    casing: 'Brass',
    image: 'https://picsum.photos/200/200?random=10',
    lastUpdated: '10 mins ago'
  },
  {
    id: '11',
    name: 'CCI Mini-Mag .22 LR 40gr CPRN',
    category: 'ammo',
    caliber: '.22 LR',
    brand: 'CCI',
    grains: 40,
    roundCount: 100,
    price: 9.99,
    cpr: 0.10,
    shippingScore: 8,
    retailer: 'Natchez SS',
    retailerRating: 4.7,
    condition: 'New',
    casing: 'Brass',
    image: 'https://picsum.photos/200/200?random=11',
    lastUpdated: '45 mins ago'
  },

  // --- FIREARMS ---
  {
    id: '101',
    name: 'Sig Sauer P365X Macro 9mm 17rd',
    category: 'firearm',
    caliber: '9mm Luger',
    brand: 'Sig Sauer',
    price: 799.99,
    shippingScore: 10,
    retailer: 'Palmetto State Armory',
    retailerRating: 4.6,
    condition: 'New',
    image: 'https://picsum.photos/200/200?random=101',
    lastUpdated: '20 mins ago'
  },
  {
    id: '102',
    name: 'Glock 19 Gen 5 FS 9mm',
    category: 'firearm',
    caliber: '9mm Luger',
    brand: 'Glock',
    price: 539.00,
    shippingScore: 9,
    retailer: 'GrabAGun',
    retailerRating: 4.8,
    condition: 'New',
    image: 'https://picsum.photos/200/200?random=102',
    lastUpdated: '1 hour ago'
  },
  {
    id: '103',
    name: 'Daniel Defense DDM4 V7 5.56 NATO',
    category: 'firearm',
    caliber: '5.56 NATO',
    brand: 'Daniel Defense',
    price: 1870.00,
    shippingScore: 10,
    retailer: 'Primary Arms',
    retailerRating: 4.9,
    condition: 'New',
    image: 'https://picsum.photos/200/200?random=103',
    lastUpdated: '3 hours ago'
  },
  {
    id: '104',
    name: 'Mossberg 500 Tactical 12 Gauge',
    category: 'firearm',
    caliber: '12 Gauge',
    brand: 'Mossberg',
    price: 450.00,
    shippingScore: 7,
    retailer: 'Buds Gun Shop',
    retailerRating: 4.5,
    condition: 'New',
    image: 'https://picsum.photos/200/200?random=104',
    lastUpdated: '5 hours ago'
  },
  {
    id: '105',
    name: 'Ruger 10/22 Carbine .22 LR',
    category: 'firearm',
    caliber: '.22 LR',
    brand: 'Ruger',
    price: 269.99,
    shippingScore: 8,
    retailer: 'Sportsmans Warehouse',
    retailerRating: 4.4,
    condition: 'New',
    image: 'https://picsum.photos/200/200?random=105',
    lastUpdated: 'Just now'
  },

  // --- PARTS ---
  {
    id: '201',
    name: 'Magpul PMAG 30 AR/M4 GEN M3',
    category: 'part',
    brand: 'Magpul',
    price: 12.30,
    shippingScore: 9,
    retailer: 'Lanbos Armory',
    retailerRating: 5.0,
    condition: 'New',
    image: 'https://picsum.photos/200/200?random=201',
    lastUpdated: '10 mins ago'
  },
  {
    id: '202',
    name: 'Holosun HS507C X2 Red Dot Sight',
    category: 'part',
    brand: 'Holosun',
    price: 309.99,
    shippingScore: 10,
    retailer: 'MidwayUSA',
    retailerRating: 4.9,
    condition: 'New',
    image: 'https://picsum.photos/200/200?random=202',
    lastUpdated: '4 hours ago'
  }
];

export const TRENDING_METRICS = [
  { label: '9mm Floor', value: '$0.23', trend: 'down' },
  { label: '5.56 Floor', value: '$0.44', trend: 'up' },
  { label: '.22LR Floor', value: '$0.05', trend: 'flat' },
  { label: 'Active Retailers', value: '104', trend: 'up' },
];